### ISSUE TITLE
Occasionally getting empty result from rest sensor

### ISSUE THREAD

**Issue by gcoan** [8none1/octopus_powerups#6]
A couple of times I've had a completely empty result from the rest sensor, eg at 17:25 today the free electricity went empty (ie not the null response, completely empty):
![image](https://github.com/user-attachments/assets/af4931cf-848b-405c-b69b-93505e6c15ef)

Can see the state change in the log file. Ignore the unknown state from this morning, that was my internet turned off 
![image](https://github.com/user-attachments/assets/7e8db47b-0e4f-45ab-a331-8c0a13ab3f32)

Error in the log file that the response couldn't be parsed
![image](https://github.com/user-attachments/assets/c5581c45-4d22-4dc5-8a32-0b849817dcf7)

**Comment by 8none1** [comment]
Curious.

If I look at commits made today I see this:

![image](https://github.com/user-attachments/assets/91880230-b996-4ac2-b110-23d14d82b8d1)

Looking at the 09:15 commit specifically I see this:

https://github.com/8none1/octopus_powerups/commit/63fd66c5dd6e072f8cd662127627c3d99a13d94a

which looks like it checked in a blank file.

This suggests that the cron job my end ran, `$something` went wrong and it uploaded a blank file.

I'll grab some logs from the Google Apps Script and see if there are any clues and add some more logging on the cron job to see why it's sad.

At the very least, if the script fails it shouldn't upload at all rather than uploading a blank file.

**Comment by 8none1** [comment]
Yes indeed, the script failed to run.

![image](https://github.com/user-attachments/assets/ab2c52c7-68e9-461a-92a4-06bed4373555)

But it seems the reason is a secret.

![image](https://github.com/user-attachments/assets/5d5b7e2a-0b1f-4881-b4dc-b3d03007c3ac)


Ok, I think that the correct course of action is to be tolerant of failure and have the updater do nothing if it doesn't get back a valid JSON object.  This will reduce spurious commits to Github and should solve the problem.

**Comment by 8none1** [comment]
Looks like it ran.  Let's keep an eye on it for a few days and see how it looks now.  Thanks for reporting this :+1: .

**Comment by gcoan** [comment]
Thanks for looking into it, I thought I'd seen it happen before but was able to clearly trace this one. 

Power up session tomorrow after todays poor solar 😀👍

**Comment by 8none1** [comment]
Looks like this has stopped the spurious uploads.  I'm going to close it as fixed, but if you notice it come back let me know.  Thanks for reporting this issue!
