### ISSUE TITLE
JSON/email mismatch

### ISSUE THREAD

**Issue by catch56** [8none1/octopus_powerups#8]
This may not be a bug, but opening in case:

I got an e-mail for a power-up today (10th October 2024) for 11:30am to 1:30pm.

However the JSON shows this as 10am to 12pm:

```[{"start":"2024-10-10T10:00:00.000Z","end":"2024-10-10T12:00:00.000Z"}]```

There are probably  two possiibilities:

1. The email parser picked up the wrong date.

2. We live in different parts of the operator and get different powerup times.

I'm assuming it's #2, and that this means I should look into self-hosting the email parsing logic from my own emails, but opening an issue just to double check.

**Comment by 8none1** [comment]
Note that the times in the JSON file are in UTC, hence the `Z` at the end.  So that's (currently) 11am BST -> 1pm BST.

Even factoring the time zone correction, it's still out by 30 mins.

It does indeed look like option 2 since my power up times were correct.  I have a friend in Suffolk and he didn't even get a Power Up today, so it looks like they are getting more localised as time goes on.

You have the option of self hosting and you can find some (sort of) instructions here:  https://github.com/8none1/octopus_powerups/issues/1#issuecomment-2308447124
If you need a hand, let me know and I'll see if I can help.

Another alternative is that I set up another instance at my end and you forward your Power Up emails to me and I can have the script output to a new JSON file.

**Comment by gcoan** [comment]
Interesting the events are getting more localised I think.  

My own power up today is 11:00-13:00 BST, same times as yours @8none1  but the power up I had a couple of days, a friend of mine who lives North of Cambridge, he didn't have one at all.

**Comment by 8none1** [comment]
> North of Cambridge

Wow, that really is getting very localised.  I wondered if it's something to do with being close to Little Barford, but that's probably a close to north Cambridge as it is to us.  

I also wondered if it was simply the email notifications system being a bit hit-and-miss, but I don't think it's that either.

**Comment by catch56** [comment]
My guess if they're localising this much is it could be which side of a substation you're on, and/or proximity to specific wind/solar sources - big difference living right next to a solar farm vs 5 miles from offshore wind etc.

Good to confirm at least partially what's going on, I'll think about how I workaround it next ;)
